### ISSUE TITLE
IVCT_RTIambassador::destroyFederationExecution should not log an error msg on exception "Federates Currently Joined"

### ISSUE THREAD

**Issue by kadijkr** [IVCTool/IVCT_Framework#292] opened 2020-07-27 13:09 UTC
Technically, this exception is an error, because the federation cannot be destroyed.
The exception will always be thrown on normal termination of the test case. That's ok, I can handle the exception.
But I cannot (to my knowledge) intercept the error message that is printed by IVCT_RTIambassador::destroyFederationExecution, nor the warning that is printed by IVCT_BaseModel::terminateRti.
So if on normal termination of my test case the SuT still is running, I will see an error msg and a warning msg logged. But my test case probably terminates with a "passed" status. That is confusing.
So IMHO IVCT_RTIambassador::destroyFederationExecution should print a warning msg or info msg, instead of an error msg.
The warning msg printed by IVCT_BaseModel::terminateRti could be changed to an info msg.

**Comment by rhzg** [comment] 2020-07-27 15:13
I agree, this is confusing or even wrong. As it is not the responsibility of the IVCT_RTIambassador to decide if this request from a test case shall be considered as failure or as intended.

So how about changing all error loggings into neural trace loggings? I believe the IVCT_RTIambassador shall just re-throw any exception and let the use case decide on the appropriate classification.

**Comment by rhzg** [comment] 2020-07-27 15:21
the same argument would be true for the IVCT_LoggingFederateAmbassador, as it should only do logging without judging

**Comment by kadijkr** [comment] 2020-07-27 19:28
So change all error (and warning?) loggings in neutral trace loggings? For (at least) the classes IVCT_RTIambassador, IVCT_LoggingFederateAmbassador, IVCT_BaseModel. Seems a good solution to me.

**Comment by rhzg** [comment] 2020-08-25 12:24
this has been implemented and is merged into the development branch

**Closed by rhzg** 2020-08-25 12:24 UTC
Labels: invalid
